image: node:10

pages:
  stage: deploy
  script:
    - yarn
    - cp config.example.js config.js
    - CDN_SERVER=$CDN_SERVER NODE_ENV=production yarn build
    - cp -r dist public
    - cp example/standalone.html public/index.html
    - find public -name '*.map' -delete
  artifacts:
    paths:
      - public
  only:
    - master

stages:
  - deploy
