image: node:10

pages:
  stage: deploy
  script:
    - yarn
    - cp config.example.js config.js
    - CDN_SERVER=$CDN_SERVER NODE_ENV=production yarn build
    - cp -r dist public
    - cp example/pages.html public/index.html
    - mkdir -p public/vendors
    - cp node_modules/normalize.css/normalize.css public/vendors/normalize.css
    - cp node_modules/leaflet/dist/leaflet.css public/vendors/leaflet.css
    - cp node_modules/jquery/dist/jquery.js public/vendors/jquery.js
    - find public -name '*.map' -delete
  artifacts:
    paths:
      - public
  only:
    - master

stages:
  - deploy
