image: node:10

pages:
  stage: deploy
  script:
    - yarn
    - yarn build
    - cp -r dist/production public
    - find public -name '*.map' -delete
  artifacts:
    paths:
      - public
  only:
    - master

stages:
  - deploy
